# Generated by Django 2.1.5 on 2020-06-13 14:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Animated Creatures', 'Animated Creatures'), ('Animated Objects', 'Animated Objects'), ('Landscapes', 'Landscapes')], default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Designs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text_content', models.TextField(default=None)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow'), ('BR', 'Brown'), ('W', 'White'), ('BL', 'Black'), ('O', 'Other')], default='Blue', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('forest', 'Forest'), ('dessert', 'Dessert'), ('city', 'City'), ('mountains', 'Mountains'), ('other', 'Other')], default='Neutral', max_length=30)),
                ('allowed_memberships', models.ManyToManyField(to='users.Membership')),
                ('category', models.ManyToManyField(to='graphics.Category')),
            ],
        ),
    ]
