# Generated by Django 2.1.5 on 2020-05-29 12:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DesignType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30, null=True)),
                ('text_content', models.TextField(null=True)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow')], default='Blue', max_length=30)),
                ('character_type', models.CharField(choices=[('H', 'Hero'), ('E', 'Enemy'), ('N', 'Neutral')], default='Blue', max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='graphic_image')),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Category')),
            ],
        ),
    ]
