# Generated by Django 2.1.5 on 2020-05-28 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GraphicDesigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=30)),
                ('text_content', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='graphic_image')),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
