# Generated by Django 2.1.5 on 2020-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designtype',
            name='text_content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='designtype',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
