# Generated by Django 2.1.5 on 2020-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0003_auto_20200529_1500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='designtype',
            name='name',
        ),
        migrations.AlterField(
            model_name='designtype',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
