# Generated by Django 2.1.5 on 2020-06-01 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_auto_20200529_1504'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DesignType',
            new_name='Creature',
        ),
    ]
