# Generated by Django 2.1.5 on 2020-06-01 09:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0005_auto_20200601_1054'),
    ]

    operations = [
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text_content', models.TextField(default=None)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow'), ('BR', 'Brown'), ('W', 'White'), ('BL', 'Black'), ('O', 'Other')], default='Blue', max_length=30)),
                ('object_type', models.CharField(choices=[('V', 'Vegetation'), ('Man-Made', (('wood', 'Wood'), ('stone', 'Stone'))), ('N', 'Neutral')], default='Blue', max_length=30)),
                ('image', models.ImageField(default='default.jpg', upload_to='graphic_image')),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Category')),
            ],
        ),
        migrations.AlterField(
            model_name='creature',
            name='color',
            field=models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow'), ('BR', 'Brown'), ('W', 'White'), ('BL', 'Black'), ('O', 'Other')], default='Blue', max_length=30),
        ),
    ]
