# Generated by Django 2.1.5 on 2020-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0008_auto_20200601_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.ForeignKey(on_delete=False, to='graphics.Category'),
        ),
    ]
