# Generated by Django 2.1.5 on 2020-06-02 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0009_auto_20200601_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Category'),
        ),
    ]
