# Generated by Django 2.1.5 on 2020-06-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0010_auto_20200602_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
