# Generated by Django 2.1.5 on 2020-06-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0011_auto_20200602_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Animated Creatures', 'Animated Creatures'), ('Animated Objects', 'Animated Objects'), ('Landscapes', 'Landscapes')], default='Animated Creatures', max_length=20),
        ),
    ]
