# Generated by Django 2.1.5 on 2020-06-03 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0012_auto_20200602_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='character_type',
            field=models.CharField(choices=[('H', 'Main Character'), ('E', 'Villain'), ('N', 'Neutral')], default='Blue', max_length=30),
        ),
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/creatures'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('V', 'Vegetation'), ('Man-Made', (('wood', 'Wood'), ('stone', 'Stone'))), ('O', 'Other')], default='Blue', max_length=30),
        ),
    ]
