# Generated by Django 2.1.5 on 2020-06-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('graphics', '0013_auto_20200603_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='creature',
            name='allowed_memberships',
            field=models.ManyToManyField(to='users.Membership'),
        ),
    ]
