# Generated by Django 2.1.5 on 2020-06-05 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('graphics', '0016_remove_creature_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creature',
            name='allowed_memberships',
        ),
        migrations.AddField(
            model_name='creature',
            name='allowed_memberships',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Membership'),
        ),
    ]
