# Generated by Django 2.1.5 on 2020-06-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0017_auto_20200605_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
