# Generated by Django 2.1.5 on 2020-06-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0019_auto_20200606_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creature',
            name='character_type',
            field=models.CharField(choices=[('H', 'Main Character'), ('E', 'Villain'), ('N', 'Neutral')], default='Neutral', max_length=30),
        ),
        migrations.AlterField(
            model_name='landscape',
            name='landscape_type',
            field=models.CharField(choices=[('forest', 'Forest'), ('dessert', 'Dessert'), ('city', 'City'), ('mountains', 'Mountains'), ('other', 'Other')], default='Other', max_length=30),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.CharField(choices=[('V', 'Vegetation'), ('Man-Made', (('wood', 'Wood'), ('stone', 'Stone'))), ('O', 'Other')], default='Other', max_length=30),
        ),
    ]
