# Generated by Django 2.1.5 on 2020-06-09 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('graphics', '0020_auto_20200606_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreaturePremium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text_content', models.TextField(default=None)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow'), ('BR', 'Brown'), ('W', 'White'), ('BL', 'Black'), ('O', 'Other')], default='Blue', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('character_type', models.CharField(choices=[('H', 'Main Character'), ('E', 'Villain'), ('N', 'Neutral')], default='Neutral', max_length=30)),
                ('allowed_memberships', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Membership')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='Creature',
            new_name='CreatureFree',
        ),
        migrations.RemoveField(
            model_name='landscape',
            name='allowed_memberships',
        ),
        migrations.RemoveField(
            model_name='object',
            name='allowed_memberships',
        ),
    ]
