# Generated by Django 2.1.5 on 2020-06-11 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('graphics', '0022_auto_20200610_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creaturefree',
            name='allowed_memberships',
        ),
        migrations.AddField(
            model_name='creaturefree',
            name='allowed_memberships',
            field=models.ManyToManyField(to='users.Membership'),
        ),
    ]
