# Generated by Django 2.1.5 on 2020-06-13 09:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('graphics', '0023_auto_20200611_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Landscape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text_content', models.TextField(default=None)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow'), ('BR', 'Brown'), ('W', 'White'), ('BL', 'Black'), ('O', 'Other')], default='Blue', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('landscape_type', models.CharField(choices=[('forest', 'Forest'), ('dessert', 'Dessert'), ('city', 'City'), ('mountains', 'Mountains'), ('other', 'Other')], default='Other', max_length=30)),
                ('allowed_memberships', models.ManyToManyField(to='users.Membership')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('text_content', models.TextField(default=None)),
                ('color', models.CharField(choices=[('B', 'Blue'), ('G', 'Green'), ('R', 'Red'), ('Y', 'Yellow'), ('BR', 'Brown'), ('W', 'White'), ('BL', 'Black'), ('O', 'Other')], default='Blue', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('date_made', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_type', models.CharField(choices=[('V', 'Vegetation'), ('Man-Made', (('wood', 'Wood'), ('stone', 'Stone'))), ('O', 'Other')], default='Other', max_length=30)),
                ('allowed_memberships', models.ManyToManyField(to='users.Membership')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='graphics.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='CreatureFree',
            new_name='Creature',
        ),
        migrations.RemoveField(
            model_name='creaturepremium',
            name='allowed_memberships',
        ),
        migrations.RemoveField(
            model_name='creaturepremium',
            name='category',
        ),
        migrations.RemoveField(
            model_name='landscapefree',
            name='category',
        ),
        migrations.RemoveField(
            model_name='landscapepremium',
            name='category',
        ),
        migrations.RemoveField(
            model_name='objectfree',
            name='category',
        ),
        migrations.RemoveField(
            model_name='objectpremium',
            name='category',
        ),
        migrations.DeleteModel(
            name='CreaturePremium',
        ),
        migrations.DeleteModel(
            name='LandscapeFree',
        ),
        migrations.DeleteModel(
            name='LandscapePremium',
        ),
        migrations.DeleteModel(
            name='ObjectFree',
        ),
        migrations.DeleteModel(
            name='ObjectPremium',
        ),
    ]
