# Generated by Django 2.1.5 on 2020-06-13 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('graphics', '0024_auto_20200613_1153'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Creature',
            new_name='Designs',
        ),
        migrations.RemoveField(
            model_name='landscape',
            name='allowed_memberships',
        ),
        migrations.RemoveField(
            model_name='landscape',
            name='category',
        ),
        migrations.RemoveField(
            model_name='object',
            name='allowed_memberships',
        ),
        migrations.RemoveField(
            model_name='object',
            name='category',
        ),
        migrations.DeleteModel(
            name='Landscape',
        ),
        migrations.DeleteModel(
            name='Object',
        ),
    ]
