# Generated by Django 2.1.5 on 2020-06-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0026_auto_20200613_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designs',
            name='landscape_type',
        ),
    ]
